spring:
  application:
    name: izumi-boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/app?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
server:
  port: 8080
logging:
  level:
    com.izumi: debug
mybatis-plus:
  mapper-locations: classpath*:com/izumi/**/mapping/*.xml

auth:
  tokenStoreType: redis # token存储类型
  expire: 2 # 过期时间（单位小时）

